In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("ecommerce_sales_analytics_5000.csv", parse_dates=['order_date'])

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   order_id          5000 non-null   int64
 1   order_date        5000 non-null   datetime64[ns]
 2   customer_id       5000 non-null   int64
 3   product_category  5000 non-null   object
 4   region            5000 non-null   object
 5   quantity          5000 non-null   int64
 6   unit_price        5000 non-null   float64
 7   discount          5000 non-null   float64
 8   payment_method    5000 non-null   object
 9   delivery_days     5000 non-null   int64
 10  customer_rating   5000 non-null   float64
 11  revenue           5000 non-null   float64
dtypes: datetime64[ns](1), float64(4), int64(4), object(3)
memory usage: 468.9+ KB

In [4]:
# map() - label hight value orders
df['payment_type']=df['payment_method'].map({
    "Card": "Digital",
    "Wallet": "Digital",
    "COD": "Cash"
})

In [5]:
# verify
df['payment_type'].unique()

array(['Digital', 'Cash'], dtype=object)

In [7]:
df[['payment_method', 'payment_type']].head()

  payment_method payment_type
0         Wallet      Digital
1           Card      Digital
2            COD         Cash
3         Wallet      Digital
4         Wallet      Digital

In [8]:
df.groupby('payment_type').size()

payment_type
Cash       1774
Digital    3226
dtype: int64

In [9]:
# apply() - Create revenue category

def revenue_category(row):
    if row["revenue"] > 500:
        return "High"
    elif row["revenue"] >= 200:
        return "Medium"
    else:
        return "Low"

df["revenue_category"] = df.apply(revenue_category, axis=1)

In [10]:
#verify
df['revenue_category'].value_counts()

revenue_category
High      3252
Medium    1098
Low        650
Name: count, dtype: int64

In [12]:
# validate logic manually
df[['revenue', 'revenue_category']].sample(10)

      revenue revenue_category
4422    32.00              Low
1878  2179.92             High
4824    82.96              Low
3688  1438.73             High
1052  1855.95             High
4829  2451.96             High
479    292.32           Medium
1246   106.96              Low
125   2887.11             High
378    553.09             High

In [13]:
# pipe() - Method chaining

def add_profit(data):
    data["profit"] = data["revenue"] * 0.20
    return data

def add_net_revenue(data):
    data["net_revenue"] = data["revenue"] - data["profit"]
    return data

df = (
    df
    .pipe(add_profit)
    .pipe(add_net_revenue)
)

In [14]:
# Verify
df[["revenue", "profit", "net_revenue"]].head()

   revenue   profit  net_revenue
0  1883.20  376.640     1506.560
1   304.10   60.820      243.280
2   644.35  128.870      515.480
3  2569.90  513.980     2055.920
4   468.56   93.712      374.848