In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv("dirty_cafe_sales.csv")
df.head()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11

In [8]:
df_sorted=df.sort_values(by=['Quantity', 'Price Per Unit'], ascending=[False, True])
print("Sorted DataFrame: ")
df_sorted.head()

Sorted DataFrame:

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
189,TXN_2643815,Cookie,UNKNOWN,1.0,3.0,ERROR,NaN,2023-12-06
743,TXN_1090854,Cookie,UNKNOWN,1.0,3.0,Credit Card,In-store,2023-01-07
978,TXN_9911345,Cookie,UNKNOWN,1.0,1.0,Digital Wallet,UNKNOWN,2023-04-14
1447,TXN_9503369,Cookie,UNKNOWN,1.0,1.0,NaN,Takeaway,NaN
2515,TXN_3174336,Cookie,UNKNOWN,1.0,1.0,NaN,NaN,2023-07-17

In [10]:
# rank
df['RankWith Price Per Unit']=df.groupby('Quantity')['Price Per Unit'].rank(method='dense', ascending=False)
print("Price Per Unit rank with Quantity: ", df)

Price Per Unit rank with Quantity:       Transaction ID      Item Quantity Price Per Unit Total Spent  \
0       TXN_1961373    Coffee        2            2.0         4.0
1       TXN_4977031      Cake        4            3.0        12.0
2       TXN_4271903    Cookie        4            1.0       ERROR
3       TXN_7034554     Salad        2            5.0        10.0
4       TXN_3160411    Coffee        2            2.0         4.0
...             ...       ...      ...            ...         ...
9995    TXN_7672686    Coffee        2            2.0         4.0
9996    TXN_9659401       NaN        3            NaN         3.0
9997    TXN_5255387    Coffee        4            2.0         8.0
9998    TXN_7695629    Cookie        3            NaN         3.0
9999    TXN_6170729  Sandwich        3            4.0        12.0

      Payment Method  Location Transaction Date  RankWith Price Per Unit
0        Credit Card  Takeaway       2023-09-08                      6.0
1               Cash  In-store       2023-05-16                      5.0
2        Credit Card  In-store       2023-07-19                      8.0
3            UNKNOWN   UNKNOWN       2023-04-27                      3.0
4     Digital Wallet  In-store       2023-06-11                      6.0
...              ...       ...              ...                      ...
9995             NaN   UNKNOWN       2023-08-30                      6.0
9996  Digital Wallet       NaN       2023-06-02                      NaN
9997  Digital Wallet       NaN       2023-03-02                      6.0
9998  Digital Wallet       NaN       2023-12-02                      NaN
9999            Cash  In-store       2023-11-07                      4.0

[10000 rows x 9 columns]